theme: jekyll-theme-cayman
title: [Matt Gagliano]
permalink: /blog/:year/:month/:day/:title
description: [ğŸ“CT/NY ğŸ¢ Product Manager @ Veritonic ğŸ¨ UI/UX Design]
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
