theme: jekyll-theme-cayman
title: Matt Gagliano
description: [ğŸ“CT/NY ğŸ¢ Product Manager @ Veritonic ğŸ¨ UI/UX Design]
    
# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
paginate: 3
paginate_path: "/page:num/"