theme: jekyll-theme-cayman
title: [Matt Gagliano]
permalink: /blog/:year/:month/:day/:title
description: [ğŸ“CT/NY  ğŸ¢ Product Manager @ <a href="https://www.veritonic.com" target="_blank">Veritonic</a>]
